### ISSUE TITLE
Null relation caused to error

### ISSUE THREAD

**Issue by aivanovbelkacar** [theofidry/EloquentSerializer#7]
What if serialized model has a null relation in https://github.com/theofidry/EloquentSerializer/blob/master/src/Serializer/Normalizer/EloquentModelNormalizer.php#L93 ?
Should it be a check on not null?

**Comment by theofidry** [comment]
Wouldn't that field appears as null in the attributes? I might be wrong but then I think reproducing it should be easy

**Comment by aivanovbelkacar** [comment]
Oh, my fault. Yes, relation is set to null and all is ok. Problem is only with collections (e.g. BelongsToMany relation). \Illuminate\Database\Eloquent\Collection class really has no method with name 'getForeignKey'. How could it be solved?

**Comment by theofidry** [comment]
Then you have something like that:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    /**
     * The roles that belong to the user.
     */
    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }
}
```

and `belongsToMany()` returns an `EloquentRelation` object, which is what is being used
